# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - run: mvn clean compile

    # steps:
    # - uses: actions/checkout@v2
    
    # - name: GitHub Action for Maven
    #   uses: LucaFeger/action-maven-cli@1.1.0
    #   run: clean compile
      # args = "clean install"0
    # - name: Maven Install
    #   run: mvn clean compile
